name: DEPLOY

on:
  push:
    branches:
      - main

jobs:
  build:
    name: '🚀 Build & Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Copy Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build & Deploy
        run: |
          git remote set-url origin https://${{ secrets.TOKEN }}@github.com/humbruno/condition-editor.git
          npm run deploy
