name: DEPLOY

on:
  push:
    branches:
      - main

jobs:
  build:
    name: '🚀 Build & Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Copy Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build & Deploy
        run: git config --global user.email $MY_EMAIL git config --global user.name $MY_NAME git remote set-url origin https://$MY_NAME:${{ secrets.MY_PASSWORD }}@github.com/your_name/your_repository.git npm run deploy
